import { SignIn, SignInButton, SignOutButton } from "@clerk/nextjs";
import Head from "next/head";
import { text } from "stream/consumers";

import { api } from "~/utils/api";

export default function Home() {
  return (
    <>
      <Head>
        <title>ML T3 ForTablet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-slate-50 to-slate-700 gap-10">
        <div className="bg-slate-200 gap-10 flex flex-col p-10 justify-evenly items-center rounded">
          <img rel="icon" src="/logo.png"></img>
          <div>
            <div className="flex flex-col gap-10 justify-center items-center rounded min-w-100">
              <div className="bg-slate-400 px-10 rounded">
                <p>Accedi</p>
              </div>
              <div className="bg-slate-400 px-10 rounded">
                <p>Registrati</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
